import:
  - display/desktop/xsetroot
  - display/color/wombat
  - display/client
  - display/tags
  - display/status/notice
  #- display/status/music/mpd
  - display/status/volume
  #- display/status/network
  #- display/status/disk
  - display/status/memory
  - display/status/power
  - display/status/load
  - display/status/time
  - display/status/arrange
  - control/mouse
  - control/keyboard/qwerty
  - control/keyboard/qwerty/arrange_by_number
  - control/keyboard/qwerty/client
  - control/keyboard/qwerty/detach
  - control/keyboard/qwerty/focus_by_letter
  - control/keyboard/qwerty/focus_by_number
  - control/keyboard/qwerty/focus
  - control/keyboard/qwerty/group
  - control/keyboard/qwerty/launch
  - control/keyboard/qwerty/layout_by_number
  - control/keyboard/qwerty/layout
  - control/keyboard/qwerty/menu
  - control/keyboard/qwerty/move_by_number
  - control/keyboard/qwerty/move
  - control/keyboard/qwerty/swap_by_number
  - control/keyboard/qwerty/swap
  - control/keyboard/qwerty/zoom

prefer:
  terminal: urxvt
  browser: chromium
  editor: gvim
  filer: pcmanfm

display:
  bar: bottom
  font: "xft:Sans-9"
  border: 5
  column:
    mode: default
    rule: |
      /.*/ -> 50+50
  client:
    rule: |
      /^pcmanfm:/ group=0
      /^firefox:/ group=0

      /^chromium:/ group=0 continue=1
      /^chromium:Chromium:Task Manager/ floating=on
      /^chromium:Chromium:Chromium Preferences$/ floating=on

      /^sonata:/ floating=on allow=+activate
      /:MPlayer:/ floating=on
      /^xmessage:/ floating=on
      /^skype:/ floating=on
      /^arandr:/ floating=on
      /^wicd-client/ floating=on
      /^<nil>:<nil>:Event Tester$/ floating=on # xev

      /^xwrits:/ tags=/./

      /^zim:/ tags=notes

      /^rdesktop/ tags=rdp floating=on

  status:
    #arrange:
      #@default: rightward
    time:
      @format: %a %b %d, %R
      refresh: 30
    volume:
      @mixer: Master
    power:
      @battery: BAT0
    disk:
      @path: $HOME
    network:
      instances:
        - @interface: wlan0
          refresh: 60
        - @interface: eth0
          refresh: 60
    notice:
      control:
        mouse_action:
          wheel_up: focus_next_view
          wheel_down: focus_previous_view

script:
  - after: |
      launch 'witray'

      {
        'claws-mail' => 'mail',
        'liferea'    => 'news',
        'chromium'   => 'www',
      }.
      each do |app, tag|
        launch "pgrep #{app} || wihack -tags #{tag} #{app}"
      end

control:
  action:
    wallpaper: |
      system 'hsetroot', '-full', Dir['Pictures/Backgrounds/*.*'].sample

    desktop: | # dock laptop to my desk
      system 'xrandr --output HDMI1 --auto --output LVDS1 --off --dpi 96'
      system 'xset dpms force on' # wake up monitor from power saving mode
      system 'marble-mouse left'
      system 'setxkbmap us -option ""'
      action 'reload' # reposition witray & update shortcuts to new xkbmap

    laptop: | # undock laptop from my desk
      system 'xrandr --output LVDS1 --auto --output HDMI1 --off --output VGA1 --off --dpi 96'
      system 'setxkbmap qwerty -option ""'
      action 'reload' # reposition witray & update shortcuts to new xkbmap

    projector: | # display through a projector
      system 'xrandr --output VGA1 --auto --output LVDS1 --off --dpi 96'
      system 'xset dpms force on' # wake up monitor from power saving mode

    autotop: | # recover from bad xrandr
      system 'xrandr --auto --dpi 96'
      system 'xset dpms force on' # wake up monitor from power saving mode

    suspend: | # put laptop to sleep
      action 'laptop'
      launch 'xlock'
      system 'sudo pm-suspend'
